USE SCHEMA ANALYTICS_DB.SILVER;

CREATE OR REPLACE TABLE ORDERS (
  ORDER_ID STRING NOT NULL,
  CUSTOMER_ID STRING NOT NULL,
  PRODUCT_ID STRING NOT NULL,
  ORDER_DATE DATE NOT NULL,
  QUANTITY NUMBER,
  UNIT_PRICE NUMBER(10, 2),
  REGION_ID STRING,
  LOAD_TIMESTAMP TIMESTAMP_NTZ,
  PRIMARY KEY (ORDER_ID)
);
