USE SCHEMA ANALYTICS_DB.SILVER;

CREATE OR REPLACE TASK SILVER_ORDERS_TASK
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE = '5 MINUTE'
WHEN
  SYSTEM$STREAM_HAS_DATA('RAW_DB.BRONZE.BRONZE_EVENTS_STREAM')
AS
  CALL SILVER_ORDERS_SPROC();

-- Task is created SUSPENDED by default; resume manually once verified (deliberately not auto-resumed by CI/CD)
