USE SCHEMA ANALYTICS_DB.GOLD;


CREATE OR REPLACE TABLE DIM_CUSTOMERS AS
SELECT DISTINCT
  CUSTOMER_ID,
  CUSTOMER_NAME,
  EMAIL,
  REGION_ID,
  CUSTOMER_SEGMENT,
  CURRENT_TIMESTAMP() AS LOADED_AT
FROM ANALYTICS_DB.SILVER.CUSTOMERS;

CREATE OR REPLACE TABLE DIM_PRODUCTS AS
SELECT DISTINCT
  PRODUCT_ID,
  PRODUCT_NAME,
  CATEGORY,
  BRAND,
  LIST_PRICE,
  CURRENT_TIMESTAMP() AS LOADED_AT
FROM ANALYTICS_DB.SILVER.PRODUCTS;
