USE SCHEMA ANALYTICS_DB.GOLD;

CREATE OR REPLACE TABLE FACT_ORDERS (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  PRODUCT_ID STRING,
  ORDER_DATE DATE,
  REGION_ID STRING,
  QUANTITY NUMBER,
  REVENUE NUMBER(12, 2)
)
CLUSTER BY (ORDER_DATE, REGION_ID);

INSERT INTO FACT_ORDERS
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  PRODUCT_ID,
  ORDER_DATE,
  REGION_ID,
  QUANTITY,
  QUANTITY * UNIT_PRICE AS REVENUE
FROM ANALYTICS_DB.SILVER.ORDERS;
