CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::051826736311:role/Snowflake_Storage_Role'
STORAGE_ALLOWED_LOCATIONS = ('s3://ecommerce-raw-events-figler');

USE SCHEMA RAW_DB.BRONZE;

CREATE OR REPLACE STAGE BRONZE_STAGE
  URL = 's3://ecommerce-raw-events-figler/'
  STORAGE_INTEGRATION = S3_INT
  FILE_FORMAT = (TYPE = JSON);
