USE SCHEMA RAW_DB.BRONZE;

CREATE OR REPLACE PIPE BRONZE_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW_EVENTS (RAW_PAYLOAD, FILE_NAME)
FROM (
  SELECT
    $1,
    METADATA$FILENAME
  FROM @BRONZE_STAGE
)
FILE_FORMAT = (TYPE = JSON);
