-- Repeatable: re-applied whenever this file's content changes (schemachange R__ convention).
-- Self-documenting schema pass (Phase 8): column/table COMMENTs feed docs/data_dictionary.md.

COMMENT ON TABLE RAW_DB.BRONZE.RAW_EVENTS IS 'Bronze landing table: raw event payloads as received from S3, zero transformation.';
ALTER TABLE RAW_DB.BRONZE.RAW_EVENTS MODIFY COLUMN RAW_PAYLOAD COMMENT 'Full raw event JSON payload exactly as received, no schema-on-write.';
ALTER TABLE RAW_DB.BRONZE.RAW_EVENTS MODIFY COLUMN FILE_NAME COMMENT 'Source S3 object name, captured via METADATA$FILENAME at ingest time.';
ALTER TABLE RAW_DB.BRONZE.RAW_EVENTS MODIFY COLUMN LOAD_TIMESTAMP COMMENT 'Timestamp the row was ingested into Bronze by Snowpipe.';

COMMENT ON TABLE ANALYTICS_DB.SILVER.ORDERS IS 'Silver: cleaned, typed, deduplicated order events parsed from Bronze RAW_EVENTS.';
ALTER TABLE ANALYTICS_DB.SILVER.ORDERS MODIFY COLUMN ORDER_ID COMMENT 'Unique order identifier, primary key, deduplicated on load.';
ALTER TABLE ANALYTICS_DB.SILVER.ORDERS MODIFY COLUMN CUSTOMER_ID COMMENT 'Foreign key to SILVER.CUSTOMERS / GOLD.DIM_CUSTOMERS.';
ALTER TABLE ANALYTICS_DB.SILVER.ORDERS MODIFY COLUMN PRODUCT_ID COMMENT 'Foreign key to SILVER.PRODUCTS / GOLD.DIM_PRODUCTS.';
ALTER TABLE ANALYTICS_DB.SILVER.ORDERS MODIFY COLUMN ORDER_DATE COMMENT 'Calendar date the order was placed, parsed from the raw event payload.';
ALTER TABLE ANALYTICS_DB.SILVER.ORDERS MODIFY COLUMN QUANTITY COMMENT 'Units of the product ordered.';
ALTER TABLE ANALYTICS_DB.SILVER.ORDERS MODIFY COLUMN UNIT_PRICE COMMENT 'Price per unit at time of order, 2 decimal places.';
ALTER TABLE ANALYTICS_DB.SILVER.ORDERS MODIFY COLUMN REGION_ID COMMENT 'Region the order was placed in.';
ALTER TABLE ANALYTICS_DB.SILVER.ORDERS MODIFY COLUMN LOAD_TIMESTAMP COMMENT 'Timestamp the row was written into Silver by SILVER_ORDERS_SPROC.';

COMMENT ON TABLE ANALYTICS_DB.SILVER.CUSTOMERS IS 'Silver: customer master data (mocked seed data, no upstream CRM source in this project).';
ALTER TABLE ANALYTICS_DB.SILVER.CUSTOMERS MODIFY COLUMN CUSTOMER_ID COMMENT 'Unique customer identifier, primary key.';
ALTER TABLE ANALYTICS_DB.SILVER.CUSTOMERS MODIFY COLUMN CUSTOMER_NAME COMMENT 'Customer full name.';
ALTER TABLE ANALYTICS_DB.SILVER.CUSTOMERS MODIFY COLUMN EMAIL COMMENT 'Customer email address.';
ALTER TABLE ANALYTICS_DB.SILVER.CUSTOMERS MODIFY COLUMN REGION_ID COMMENT 'Customer''s home region.';
ALTER TABLE ANALYTICS_DB.SILVER.CUSTOMERS MODIFY COLUMN SIGNUP_DATE COMMENT 'Date the customer account was created.';
ALTER TABLE ANALYTICS_DB.SILVER.CUSTOMERS MODIFY COLUMN CUSTOMER_SEGMENT COMMENT 'Business segment, e.g. Retail or Wholesale.';
ALTER TABLE ANALYTICS_DB.SILVER.CUSTOMERS MODIFY COLUMN LOAD_TIMESTAMP COMMENT 'Timestamp the row was loaded into Silver.';

COMMENT ON TABLE ANALYTICS_DB.SILVER.PRODUCTS IS 'Silver: product master data (mocked seed data, no upstream PIM source in this project).';
ALTER TABLE ANALYTICS_DB.SILVER.PRODUCTS MODIFY COLUMN PRODUCT_ID COMMENT 'Unique product identifier, primary key.';
ALTER TABLE ANALYTICS_DB.SILVER.PRODUCTS MODIFY COLUMN PRODUCT_NAME COMMENT 'Product display name.';
ALTER TABLE ANALYTICS_DB.SILVER.PRODUCTS MODIFY COLUMN CATEGORY COMMENT 'Top-level product category.';
ALTER TABLE ANALYTICS_DB.SILVER.PRODUCTS MODIFY COLUMN BRAND COMMENT 'Product brand.';
ALTER TABLE ANALYTICS_DB.SILVER.PRODUCTS MODIFY COLUMN LIST_PRICE COMMENT 'Standard list price, 2 decimal places.';
ALTER TABLE ANALYTICS_DB.SILVER.PRODUCTS MODIFY COLUMN LOAD_TIMESTAMP COMMENT 'Timestamp the row was loaded into Silver.';

COMMENT ON TABLE ANALYTICS_DB.GOLD.DIM_CUSTOMERS IS 'Gold dimension: customer descriptive attributes for BI joins/filters.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_CUSTOMERS MODIFY COLUMN CUSTOMER_ID COMMENT 'Unique customer identifier, joins to FACT_ORDERS.CUSTOMER_ID.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_CUSTOMERS MODIFY COLUMN CUSTOMER_NAME COMMENT 'Customer full name.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_CUSTOMERS MODIFY COLUMN EMAIL COMMENT 'Customer email address.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_CUSTOMERS MODIFY COLUMN REGION_ID COMMENT 'Customer''s home region.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_CUSTOMERS MODIFY COLUMN CUSTOMER_SEGMENT COMMENT 'Business segment, e.g. Retail or Wholesale.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_CUSTOMERS MODIFY COLUMN LOADED_AT COMMENT 'Timestamp this dimension row was (re)built.';

COMMENT ON TABLE ANALYTICS_DB.GOLD.DIM_PRODUCTS IS 'Gold dimension: product descriptive attributes for BI joins/filters.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_PRODUCTS MODIFY COLUMN PRODUCT_ID COMMENT 'Unique product identifier, joins to FACT_ORDERS.PRODUCT_ID.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_PRODUCTS MODIFY COLUMN PRODUCT_NAME COMMENT 'Product display name.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_PRODUCTS MODIFY COLUMN CATEGORY COMMENT 'Top-level product category.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_PRODUCTS MODIFY COLUMN BRAND COMMENT 'Product brand.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_PRODUCTS MODIFY COLUMN LIST_PRICE COMMENT 'Standard list price, 2 decimal places.';
ALTER TABLE ANALYTICS_DB.GOLD.DIM_PRODUCTS MODIFY COLUMN LOADED_AT COMMENT 'Timestamp this dimension row was (re)built.';

COMMENT ON TABLE ANALYTICS_DB.GOLD.FACT_ORDERS IS 'Gold fact: one row per order, clustered by (ORDER_DATE, REGION_ID) for BI query pruning.';
ALTER TABLE ANALYTICS_DB.GOLD.FACT_ORDERS MODIFY COLUMN ORDER_ID COMMENT 'Unique order identifier.';
ALTER TABLE ANALYTICS_DB.GOLD.FACT_ORDERS MODIFY COLUMN CUSTOMER_ID COMMENT 'Foreign key to DIM_CUSTOMERS.CUSTOMER_ID.';
ALTER TABLE ANALYTICS_DB.GOLD.FACT_ORDERS MODIFY COLUMN PRODUCT_ID COMMENT 'Foreign key to DIM_PRODUCTS.PRODUCT_ID.';
ALTER TABLE ANALYTICS_DB.GOLD.FACT_ORDERS MODIFY COLUMN ORDER_DATE COMMENT 'Calendar date the order was placed; part of the clustering key.';
ALTER TABLE ANALYTICS_DB.GOLD.FACT_ORDERS MODIFY COLUMN REGION_ID COMMENT 'Region the order was placed in; part of the clustering key.';
ALTER TABLE ANALYTICS_DB.GOLD.FACT_ORDERS MODIFY COLUMN QUANTITY COMMENT 'Units ordered.';
ALTER TABLE ANALYTICS_DB.GOLD.FACT_ORDERS MODIFY COLUMN REVENUE COMMENT 'QUANTITY * UNIT_PRICE at order time.';
