USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR TRANSFORM_MONITOR
WITH CREDIT_QUOTA = 10
TRIGGERS ON 80 PERCENT DO NOTIFY
ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = TRANSFORM_MONITOR;
